// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InfoType - тип хранимой информации
type InfoType int32

const (
	InfoType_INFO_TYPE_UNKNOWN   InfoType = 0
	InfoType_INFO_TYPE_TEXT      InfoType = 1
	InfoType_INFO_TYPE_FILE      InfoType = 2
	InfoType_INFO_TYPE_LOG_PASS  InfoType = 3
	InfoType_INFO_TYPE_BANK_CARD InfoType = 4
)

// Enum value maps for InfoType.
var (
	InfoType_name = map[int32]string{
		0: "INFO_TYPE_UNKNOWN",
		1: "INFO_TYPE_TEXT",
		2: "INFO_TYPE_FILE",
		3: "INFO_TYPE_LOG_PASS",
		4: "INFO_TYPE_BANK_CARD",
	}
	InfoType_value = map[string]int32{
		"INFO_TYPE_UNKNOWN":   0,
		"INFO_TYPE_TEXT":      1,
		"INFO_TYPE_FILE":      2,
		"INFO_TYPE_LOG_PASS":  3,
		"INFO_TYPE_BANK_CARD": 4,
	}
)

func (x InfoType) Enum() *InfoType {
	p := new(InfoType)
	*p = x
	return p
}

func (x InfoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InfoType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (InfoType) Type() protoreflect.EnumType {
	return &file_api_gophkeeper_proto_enumTypes[0]
}

func (x InfoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InfoType.Descriptor instead.
func (InfoType) EnumDescriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{0}
}

// AuthorizationRequest содержит информацию для регистрации и авторизации пользователя.
type AuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthorizationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// TokenResponse содержит токен зарегистрированного пользователя.
type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// EmptyResponse - пустой ответ для подтверждения успешного выполнения метода.
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{2}
}

// LogPass содержит пару логин/пароль для хранения.
type LogPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPass) Reset() {
	*x = LogPass{}
	mi := &file_api_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPass) ProtoMessage() {}

func (x *LogPass) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPass.ProtoReflect.Descriptor instead.
func (*LogPass) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *LogPass) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LogPass) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Text содержит произвольный текст для хранения.
type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_api_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// File содержит файл в бинарном формате для хранения.
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_api_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// BankCard содержит данные банковских карт для хранения.
type BankCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holder        string                 `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCard) Reset() {
	*x = BankCard{}
	mi := &file_api_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCard) ProtoMessage() {}

func (x *BankCard) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCard.ProtoReflect.Descriptor instead.
func (*BankCard) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *BankCard) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *BankCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

// AddRequest содержит данные для добавления к пользователю.
type AddRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Token       string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AddRequest_LogPass
	//	*AddRequest_Text
	//	*AddRequest_File
	//	*AddRequest_BankCard
	Payload       isAddRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *AddRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddRequest) GetPayload() isAddRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AddRequest) GetLogPass() *LogPass {
	if x != nil {
		if x, ok := x.Payload.(*AddRequest_LogPass); ok {
			return x.LogPass
		}
	}
	return nil
}

func (x *AddRequest) GetText() *Text {
	if x != nil {
		if x, ok := x.Payload.(*AddRequest_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *AddRequest) GetFile() *File {
	if x != nil {
		if x, ok := x.Payload.(*AddRequest_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *AddRequest) GetBankCard() *BankCard {
	if x != nil {
		if x, ok := x.Payload.(*AddRequest_BankCard); ok {
			return x.BankCard
		}
	}
	return nil
}

type isAddRequest_Payload interface {
	isAddRequest_Payload()
}

type AddRequest_LogPass struct {
	LogPass *LogPass `protobuf:"bytes,3,opt,name=log_pass,json=logPass,proto3,oneof"`
}

type AddRequest_Text struct {
	Text *Text `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type AddRequest_File struct {
	File *File `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

type AddRequest_BankCard struct {
	BankCard *BankCard `protobuf:"bytes,6,opt,name=bank_card,json=bankCard,proto3,oneof"`
}

func (*AddRequest_LogPass) isAddRequest_Payload() {}

func (*AddRequest_Text) isAddRequest_Payload() {}

func (*AddRequest_File) isAddRequest_Payload() {}

func (*AddRequest_BankCard) isAddRequest_Payload() {}

// AddResponse содержит идентификатор добавленных данных.
type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *AddResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteRequest содержит информацию для удаления данных по переданному идентификатору.
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type          InfoType               `protobuf:"varint,2,opt,name=type,proto3,enum=api.InfoType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteRequest) GetType() InfoType {
	if x != nil {
		return x.Type
	}
	return InfoType_INFO_TYPE_UNKNOWN
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetRequest возвращает сохраненные пользователем данные по переданному идентификатору.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type          InfoType               `protobuf:"varint,2,opt,name=type,proto3,enum=api.InfoType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *GetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetRequest) GetType() InfoType {
	if x != nil {
		return x.Type
	}
	return InfoType_INFO_TYPE_UNKNOWN
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Data определяет формат для возвращаемой информации.
type Data struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Data_LogPass
	//	*Data_Text
	//	*Data_File
	//	*Data_BankCard
	Payload       isData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_api_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Data) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Data) GetPayload() isData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Data) GetLogPass() *LogPass {
	if x != nil {
		if x, ok := x.Payload.(*Data_LogPass); ok {
			return x.LogPass
		}
	}
	return nil
}

func (x *Data) GetText() *Text {
	if x != nil {
		if x, ok := x.Payload.(*Data_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Data) GetFile() *File {
	if x != nil {
		if x, ok := x.Payload.(*Data_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Data) GetBankCard() *BankCard {
	if x != nil {
		if x, ok := x.Payload.(*Data_BankCard); ok {
			return x.BankCard
		}
	}
	return nil
}

type isData_Payload interface {
	isData_Payload()
}

type Data_LogPass struct {
	LogPass *LogPass `protobuf:"bytes,3,opt,name=log_pass,json=logPass,proto3,oneof"`
}

type Data_Text struct {
	Text *Text `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type Data_File struct {
	File *File `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

type Data_BankCard struct {
	BankCard *BankCard `protobuf:"bytes,6,opt,name=bank_card,json=bankCard,proto3,oneof"`
}

func (*Data_LogPass) isData_Payload() {}

func (*Data_Text) isData_Payload() {}

func (*Data_File) isData_Payload() {}

func (*Data_BankCard) isData_Payload() {}

// GetResponse содержит информацию о полученой приватной информации.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *GetResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetAllRequest содержит данные для получения информации о текущих сохраненных данных пользователя.
type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_api_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Info предоставляет краткую информацию о хранимой информации.
type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          InfoType               `protobuf:"varint,2,opt,name=type,proto3,enum=api.InfoType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_api_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *Info) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Info) GetType() InfoType {
	if x != nil {
		return x.Type
	}
	return InfoType_INFO_TYPE_UNKNOWN
}

func (x *Info) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetAllResponse - содержит информацию о сохраненных данных пользователя.
type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*Info                `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_api_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_api_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllResponse) GetInfo() []*Info {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_api_gophkeeper_proto protoreflect.FileDescriptor

const file_api_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x14api/gophkeeper.proto\x12\x03api\"H\n" +
	"\x14AuthorizationRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0f\n" +
	"\rEmptyResponse\";\n" +
	"\aLogPass\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1a\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\":\n" +
	"\bBankCard\x12\x16\n" +
	"\x06holder\x18\x01 \x01(\tR\x06holder\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"\xea\x01\n" +
	"\n" +
	"AddRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\blog_pass\x18\x03 \x01(\v2\f.api.LogPassH\x00R\alogPass\x12\x1f\n" +
	"\x04text\x18\x04 \x01(\v2\t.api.TextH\x00R\x04text\x12\x1f\n" +
	"\x04file\x18\x05 \x01(\v2\t.api.FileH\x00R\x04file\x12,\n" +
	"\tbank_card\x18\x06 \x01(\v2\r.api.BankCardH\x00R\bbankCardB\t\n" +
	"\apayload\"\x1d\n" +
	"\vAddResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\rDeleteRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.api.InfoTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"U\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.api.InfoTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xde\x01\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\blog_pass\x18\x03 \x01(\v2\f.api.LogPassH\x00R\alogPass\x12\x1f\n" +
	"\x04text\x18\x04 \x01(\v2\t.api.TextH\x00R\x04text\x12\x1f\n" +
	"\x04file\x18\x05 \x01(\v2\t.api.FileH\x00R\x04file\x12,\n" +
	"\tbank_card\x18\x06 \x01(\v2\r.api.BankCardH\x00R\bbankCardB\t\n" +
	"\apayload\",\n" +
	"\vGetResponse\x12\x1d\n" +
	"\x04data\x18\x01 \x01(\v2\t.api.DataR\x04data\"%\n" +
	"\rGetAllRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"[\n" +
	"\x04Info\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.api.InfoTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"/\n" +
	"\x0eGetAllResponse\x12\x1d\n" +
	"\x04info\x18\x01 \x03(\v2\t.api.InfoR\x04info*z\n" +
	"\bInfoType\x12\x15\n" +
	"\x11INFO_TYPE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eINFO_TYPE_TEXT\x10\x01\x12\x12\n" +
	"\x0eINFO_TYPE_FILE\x10\x02\x12\x16\n" +
	"\x12INFO_TYPE_LOG_PASS\x10\x03\x12\x17\n" +
	"\x13INFO_TYPE_BANK_CARD\x10\x042x\n" +
	"\x04Auth\x127\n" +
	"\x06SignUp\x12\x19.api.AuthorizationRequest\x1a\x12.api.TokenResponse\x127\n" +
	"\x06SignIn\x12\x19.api.AuthorizationRequest\x1a\x12.api.TokenResponse2\xc5\x01\n" +
	"\n" +
	"Gophkeeper\x12(\n" +
	"\x03Add\x12\x0f.api.AddRequest\x1a\x10.api.AddResponse\x120\n" +
	"\x06Delete\x12\x12.api.DeleteRequest\x1a\x12.api.EmptyResponse\x12(\n" +
	"\x03Get\x12\x0f.api.GetRequest\x1a\x10.api.GetResponse\x121\n" +
	"\x06GetAll\x12\x12.api.GetAllRequest\x1a\x13.api.GetAllResponseB\aZ\x05protob\x06proto3"

var (
	file_api_gophkeeper_proto_rawDescOnce sync.Once
	file_api_gophkeeper_proto_rawDescData []byte
)

func file_api_gophkeeper_proto_rawDescGZIP() []byte {
	file_api_gophkeeper_proto_rawDescOnce.Do(func() {
		file_api_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gophkeeper_proto_rawDesc), len(file_api_gophkeeper_proto_rawDesc)))
	})
	return file_api_gophkeeper_proto_rawDescData
}

var file_api_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_gophkeeper_proto_goTypes = []any{
	(InfoType)(0),                // 0: api.InfoType
	(*AuthorizationRequest)(nil), // 1: api.AuthorizationRequest
	(*TokenResponse)(nil),        // 2: api.TokenResponse
	(*EmptyResponse)(nil),        // 3: api.EmptyResponse
	(*LogPass)(nil),              // 4: api.LogPass
	(*Text)(nil),                 // 5: api.Text
	(*File)(nil),                 // 6: api.File
	(*BankCard)(nil),             // 7: api.BankCard
	(*AddRequest)(nil),           // 8: api.AddRequest
	(*AddResponse)(nil),          // 9: api.AddResponse
	(*DeleteRequest)(nil),        // 10: api.DeleteRequest
	(*GetRequest)(nil),           // 11: api.GetRequest
	(*Data)(nil),                 // 12: api.Data
	(*GetResponse)(nil),          // 13: api.GetResponse
	(*GetAllRequest)(nil),        // 14: api.GetAllRequest
	(*Info)(nil),                 // 15: api.Info
	(*GetAllResponse)(nil),       // 16: api.GetAllResponse
}
var file_api_gophkeeper_proto_depIdxs = []int32{
	4,  // 0: api.AddRequest.log_pass:type_name -> api.LogPass
	5,  // 1: api.AddRequest.text:type_name -> api.Text
	6,  // 2: api.AddRequest.file:type_name -> api.File
	7,  // 3: api.AddRequest.bank_card:type_name -> api.BankCard
	0,  // 4: api.DeleteRequest.type:type_name -> api.InfoType
	0,  // 5: api.GetRequest.type:type_name -> api.InfoType
	4,  // 6: api.Data.log_pass:type_name -> api.LogPass
	5,  // 7: api.Data.text:type_name -> api.Text
	6,  // 8: api.Data.file:type_name -> api.File
	7,  // 9: api.Data.bank_card:type_name -> api.BankCard
	12, // 10: api.GetResponse.data:type_name -> api.Data
	0,  // 11: api.Info.type:type_name -> api.InfoType
	15, // 12: api.GetAllResponse.info:type_name -> api.Info
	1,  // 13: api.Auth.SignUp:input_type -> api.AuthorizationRequest
	1,  // 14: api.Auth.SignIn:input_type -> api.AuthorizationRequest
	8,  // 15: api.Gophkeeper.Add:input_type -> api.AddRequest
	10, // 16: api.Gophkeeper.Delete:input_type -> api.DeleteRequest
	11, // 17: api.Gophkeeper.Get:input_type -> api.GetRequest
	14, // 18: api.Gophkeeper.GetAll:input_type -> api.GetAllRequest
	2,  // 19: api.Auth.SignUp:output_type -> api.TokenResponse
	2,  // 20: api.Auth.SignIn:output_type -> api.TokenResponse
	9,  // 21: api.Gophkeeper.Add:output_type -> api.AddResponse
	3,  // 22: api.Gophkeeper.Delete:output_type -> api.EmptyResponse
	13, // 23: api.Gophkeeper.Get:output_type -> api.GetResponse
	16, // 24: api.Gophkeeper.GetAll:output_type -> api.GetAllResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_gophkeeper_proto_init() }
func file_api_gophkeeper_proto_init() {
	if File_api_gophkeeper_proto != nil {
		return
	}
	file_api_gophkeeper_proto_msgTypes[7].OneofWrappers = []any{
		(*AddRequest_LogPass)(nil),
		(*AddRequest_Text)(nil),
		(*AddRequest_File)(nil),
		(*AddRequest_BankCard)(nil),
	}
	file_api_gophkeeper_proto_msgTypes[11].OneofWrappers = []any{
		(*Data_LogPass)(nil),
		(*Data_Text)(nil),
		(*Data_File)(nil),
		(*Data_BankCard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gophkeeper_proto_rawDesc), len(file_api_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_gophkeeper_proto_goTypes,
		DependencyIndexes: file_api_gophkeeper_proto_depIdxs,
		EnumInfos:         file_api_gophkeeper_proto_enumTypes,
		MessageInfos:      file_api_gophkeeper_proto_msgTypes,
	}.Build()
	File_api_gophkeeper_proto = out.File
	file_api_gophkeeper_proto_goTypes = nil
	file_api_gophkeeper_proto_depIdxs = nil
}
